config/routes.rb
Rails.application.routes.draw do
  root 'dates#index'
  resources :dates

  get '/ping', to: 'application#ping'
end

app/models/date_to_remember.rb
class DateToRemember < ActiveRecord::Base

  validates :title, presence: true
  validates :date, presence: true
  validates :category, presence: true

  def self.categories
    ['Other', 'Birthday', 'Travel', 'Anniversary', 'Home', 'Work', 'Event'].sort
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with name: (ENV['USERNAME'] || 'admin'), password: (ENV['PASSWORD'] || 'password'), except: [:ping]

  def ping
    render plain: 'ok', layout: false
  end

end

app/controllers/dates_controller.rb
class DatesController < ApplicationController
  def index
    params[:order] = params[:order].presence || 'date'
    params[:sort_mode] = params[:sort_mode].presence || 'asc'

    @date = DateToRemember.new
    @dates = DateToRemember.order(params[:order] => params[:sort_mode])

    # Calendar Stuff
    @earliest_date = [(@dates.any? ? @dates.pluck(:date).min : nil), Date.today].compact.min
    @latest_date = [(@dates.any? ? @dates.pluck(:date).max : nil), Date.today].compact.min

    # Date filtering
    @dates = @dates.where('date >= ? AND date <= ?', params[:start_date], params[:end_date]) if params[:start_date].present?
    @start_date = [@dates.pluck(:date).min, (params[:start_date] ? Date.parse(params[:start_date]) : nil)].compact.min
    @end_date = [@dates.pluck(:date).max, (params[:end_date] ? Date.parse(params[:end_date]) : nil)].compact.max

    # Travel Stats
    @travel_dates = @dates.where(category: 'Travel').where('end_date IS NOT null AND end_date < ?', Date.today).to_a
    @travel_count = @travel_dates.pluck(:title).uniq.size
    @travel_start = @travel_dates.pluck(:date).min
    @travel_days = @travel_dates.sum{|d| (d.end_date - d.date).to_i}
  end

  def create
    @date = DateToRemember.new(date_params)
    if @date.save
      redirect_to dates_path
    else
      render :new
    end
  end

  def new
    @date = DateToRemember.new
  end

  def edit
    @date = DateToRemember.find(params[:id])
  end

  def update
    @date = DateToRemember.find(params[:id])
    if @date.update(date_params)
      redirect_to dates_path
    else
      render :edit
    end
  end

  def destroy
    DateToRemember.find(params[:id]).destroy
    redirect_to dates_path
  end

  private

  def date_params
    params.require(:date_to_remember).permit(:date, :title, :end_date, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dates_helper.rb
module DatesHelper

  def component_date(date, end_date: nil)
    start_date = date.date
    end_date = end_date || date.end_date.presence
    return nil if end_date.nil?

    component = TimeDifference.between(start_date, end_date).in_general
    output = []
    if component[:years] > 0
      output << pluralize(component[:years], 'year')
    end

    if component[:months] > 0
      output << pluralize(component[:months], 'month')
    end

    if component[:weeks]> 0
      output << pluralize(component[:weeks], 'week')
    end

    if component[:days]> 0
      output << pluralize(component[:days], 'day')
    end

    output.join(', ')
  end
end

app/views/dates/_table.html.erb
<%= table_for dates, table_html: { class: 'table table-hover table-bordered' } do |table| %>
  <%= table.column :title, link_url: lambda { |d| edit_date_path d  } %>
  <%= table.column :category, data: -> { table.current_row.category.to_s.titleize  } %>
  <%= table.column :date, data: -> { table.current_row.date.to_s(:rfc822) }, header: 'Start Date' %>
  <%= table.column :end_date, data: -> { table.current_row.end_date ? table.current_row.end_date.to_s(:rfc822) : '-' }, header: 'End Date' %>
  <%= table.column data: -> { component_date(table.current_row) || '-' }, header: 'Duration', sortable: false %>
  <%= table.column data: -> { component_date table.current_row, end_date: Date.today }, header: (future ? 'Time Until' : 'Time Ago'), sortable: false %>
<% end %>

app/views/dates/edit.html.erb
<div class="page-header">
  <h2>
    <%= link_to 'Dates to Remember', root_path %>
    > #{@date.title.presence || @date.id}
  </h2>
</div>
<%= simple_form_for @date, html: { class: 'well' }, url: date_path(@date) do |f| %>
  <%= f.input :title %>
  <%= f.input :category, collection: DateToRemember.categories, include_blank: false %>
  <%= f.input :date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.button :submit, value: 'Update' %>
  <%= link_to 'Delete', date_path(@date), class: 'btn btn-danger', method: :delete %>
<% end %>

app/views/dates/index.html.erb
<div class="page-header">
  <% if @dates.any? %>
    <div class="pull-right">
      <div class="daterange daterange--double two"></div>
    </div>
  <% end %>
  <h2>
    Dates to Remember
    <%= link_to '+ Add', new_date_path, class: 'btn btn-xs btn-primary' %>
  </h2>
</div>
<% if @travel_count > 0 %>
  <p class="alert alert-info">You have spent <b>#{pluralize(@travel_days, 'day')}</b> traveling to <b>#{pluralize(@travel_count, 'place')}</b> since <b>#{@travel_start.to_s(:rfc822)}</b>.</p>
<% end %>
<% if @dates.select{|d| d.date > Date.today }.any? %>
  <h2 class="lead">Upcoming Events</h2>
  <%= render 'table', dates: @dates.select{|d| d.date > Date.today }, future: true %>
<% end %>
<% if @dates.select{|d| d.date <= Date.today }.any? %>
  <h2 class="lead">Past Events</h2>
  <%= render 'table', dates: @dates.select{|d| d.date <= Date.today }, future: false %>
<% else %>
  <p class="alert alert-info">You have not created any dates yet</p>
<% end %>
<script>
  $(document).ready(function() {
    if ($('.daterange .dr-input').length == 0) {
      new Calendar({
        element: $('.daterange'),
        earliest_date: "#{@earliest_date}",
        latest_date: moment("#{@latest_date}"),
        start_date: moment("#{@start_date}"),
        end_date: moment("#{@end_date}"),
        presets: true,
        callback: function() {
          var start_date = this.start_date.format('YYYY-MM-DD')
          var end_date = this.end_date.format('YYYY-MM-DD')
          window.location.href = window.location.pathname+"?"+$.param({'start_date': start_date,'end_date': end_date })
        }
      });
    }
  })
</script>

app/views/dates/new.html.erb
<div class="page-header">
  <% if @dates.any? %>
    <div class="pull-right">
      <div class="daterange daterange--double two"></div>
    </div>
  <% end %>
  <h2>
    Dates to Remember
    <%= link_to '+ Add', new_date_path, class: 'btn btn-xs btn-primary' %>
  </h2>
</div>
<% if @travel_count > 0 %>
  <p class="alert alert-info">You have spent <b>#{pluralize(@travel_days, 'day')}</b> traveling to <b>#{pluralize(@travel_count, 'place')}</b> since <b>#{@travel_start.to_s(:rfc822)}</b>.</p>
<% end %>
<% if @dates.select{|d| d.date > Date.today }.any? %>
  <h2 class="lead">Upcoming Events</h2>
  <%= render 'table', dates: @dates.select{|d| d.date > Date.today }, future: true %>
<% end %>
<% if @dates.select{|d| d.date <= Date.today }.any? %>
  <h2 class="lead">Past Events</h2>
  <%= render 'table', dates: @dates.select{|d| d.date <= Date.today }, future: false %>
<% else %>
  <p class="alert alert-info">You have not created any dates yet</p>
<% end %>
<script>
  $(document).ready(function() {
    if ($('.daterange .dr-input').length == 0) {
      new Calendar({
        element: $('.daterange'),
        earliest_date: "#{@earliest_date}",
        latest_date: moment("#{@latest_date}"),
        start_date: moment("#{@start_date}"),
        end_date: moment("#{@end_date}"),
        presets: true,
        callback: function() {
          var start_date = this.start_date.format('YYYY-MM-DD')
          var end_date = this.end_date.format('YYYY-MM-DD')
          window.location.href = window.location.pathname+"?"+$.param({'start_date': start_date,'end_date': end_date })
        }
      });
    }
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Dates</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <a aria-label="View source on Github" class="github-corner" href="https://github.com/scottrobertson/dates">
      <svg aria-hidden="true" height="80" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" viewbox="0 0 250 250" width="80">
        <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
        <path class="octo-arm" d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;"></path>
        <path class="octo-body" d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor"></path>
      </svg>
    </a>
    <css>
      .github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}
    </css>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>